//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisioterapiaUlatskawa.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expedientes
    {
        public string cedula { get; set; }
        public Nullable<System.DateTime> fechaN { get; set; }
        public string ciudad { get; set; }
        public string canton { get; set; }
        public string distrito { get; set; }
        public string diagnostico { get; set; }
        public string antecedentes { get; set; }
        public string mediUtilizados { get; set; }
        public string anteQuirurgicos { get; set; }
        public string fracturas { get; set; }
        public string anteFamiliares { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
