//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisioterapiaUlatskawa.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string cedula { get; set; }
        public Nullable<System.DateTime> fechaN { get; set; }
        public Nullable<byte> telefono { get; set; }
        public string ciudad { get; set; }
        public string canton { get; set; }
        public string distrito { get; set; }
        public string correo { get; set; }
        public string diagnostico { get; set; }
        public string antecedentes { get; set; }
        public string mediUtilizados { get; set; }
        public string anteQuirurgicos { get; set; }
        public string fracturas { get; set; }
        public string anteFamiliares { get; set; }
    }
}
