//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisioterapiaUlatskawa.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int idPago { get; set; }
        public Nullable<int> tipoPago { get; set; }
        public Nullable<double> monto { get; set; }
        public string banco { get; set; }
        public string cedula { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
        public string notas { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual TipoPago TipoPago1 { get; set; }
    }
}
